module-template: ! 'module MODULE_NAME where

'
extensions:
  OverloadedStrings: true
  GADTs: true
  KindSignatures: true
environment: ghc-7.8-unstable
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ''
ghc-args:
- -Wall
- -XLambdaCase
- -fno-warn-unused-do-bind
excluded-modules:
- Setup.hs
