module-template: ! 'module MODULE_NAME where

'
extensions:
  OverloadedStrings: true
  DeriveFoldable: true
  GADTs: true
  TypeOperators: true
  DeriveFunctor: true
  KindSignatures: true
  DeriveDataTypeable: true
  RankNTypes: true
  DeriveTraversable: true
environment: ghc-7.8-stable-14.09
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args:
- -Wall
- -XLambdaCase
- -fno-warn-unused-do-bind
- -XDataKinds
- -XDeriveGeneric
excluded-modules:
- Setup.hs
